### ISSUE TITLE
Is there a 5.3 version of the f_observation_view creation script ? 

### ISSUE THREAD

**Issue by gkowalski** [omoponfhir/omoponfhir-site-n-docs#1]
Looking for the 5.3 version of the https://github.com/omoponfhir/omoponfhir-site-n-docs/blob/main/documentation/OMOPonFHIR-OMOPv6-PSQL-Scripts.zip  to create the f_patient and f_observation view...

**Comment by gkowalski** [comment]
Hmm . We find this : https://github.com/Smart-PACER-Registry/omopv5_4_setup/blob/main/omoponfhir_v5.4_f_observation_ddl.txt
in another repo ...

**Comment by myungchoi** [comment]
Sorry for the late response. I wanted to create a repo for OMOPv5.3. And, yes, that registry will prob work. But, it could be somewhat customized for the registry.  Here is the one for OMOPv5.3.

https://github.com/omoponfhir/omopv5_3_setup
